library(rmarkdown)
library(devtools)
library(knitr)
library(pander)
library(ggplot2)
library(glmnet)
library(pls)
library(fields)


sink("../../session-info.txt", append=TRUE)
print(sessionInfo())
devtools::session_info()
writeLines("\n")
sink()
